seed: 42

models:
  separate: True
  policy:  # gaussian model
    class: "GaussianMixin"
    clip_actions: False # never enable this if use mixed precision
    clip_log_std: True
    initial_log_std: 0.0
    min_log_std: -20.0
    max_log_std: 2.0
    input_shape: "Shape.STATES"
    hiddens: [512, 256, 128]
    hidden_activation: ["elu", "elu", "elu"]
    output_shape: "Shape.ACTIONS"
    output_activation: ""
    output_scale: 1.0
  value:  # deterministic model
    class: "DeterministicMixin"
    clip_actions: False
    input_shape: "Shape.STATES"
    hiddens: [512, 256, 128]
    hidden_activation: ["elu", "elu", "elu"]
    output_shape: "Shape.ONE"
    output_activation: ""
    output_scale: 1.0

memory:
  class: "RandomMemory"
  memory_size: -1  # -1: automatically determined value

agent:
  class: "PPO"
  rollouts: 10
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 3.e-4
  learning_rate_scheduler: "KLAdaptiveLR"
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
  state_preprocessor: null
  state_preprocessor_kwargs: {}
  value_preprocessor: null
  value_preprocessor_kwargs: {}
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.01
  value_loss_scale: 1.0
  kl_threshold: 0
  rewards_shaper: null
  time_limit_bootstrap: true  # help reward stable when episode truncated
  mixed_precision: false
  # logging and checkpoint
  experiment:
    directory: "logs"
    experiment_name: ""
    write_interval: 10
    checkpoint_interval: 500
    store_separately: false
  eval:
    experiment_name: "GOOD_ACC"

trainer:
  class: "SequentialTrainer"
  timesteps: 50000
  environment_info: "log"

env_cfg:
  num_envs: 16384                # number of environments to run in parallel
  episode_length_s: 50.0        # episode length in seconds
  dt: 0.01                      # simulation timestep
  step_dt: 0.1                  # control timestep
  agent:
    num_left_agents: 1               # number of agents
    num_right_agents: 1               # number of agents
    num_observations: 12         # number of observations per agent
    num_actions: 3              # number of actions per agent
    tag_threshold: 0.5          # distance threshold for tagging
    clip_agent_velocity: 2.0   # velocity clipping range
    agent_size: 0.05            # size of agent
  arena:
    arena_size: 2.0            # edge length of arena, which would be a square
  reward:
    reward_scales:             # reward scaling factors
      tag: 1                 # award the pursuer for capturing the target, -1 if not captured
  max_visualize_FPS: 60       # maximum FPS for visualization
